import {
  Activity,
  ArrowUp,
  AudioLines,
  Brain,
  Clapperboard,
  Code,
  Image,
  Music,
  SlidersHorizontal,
  SquarePen,
  Wrench,
  ArrowDownRight,
  ArrowUpRight,
  Boxes,
  CalendarRange,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleStop,
  Clock,
  Coins,
  Columns3,
  Copy,
  Download,
  Gauge,
  Inbox,
  KeyRound,
  ListFilter,
  LoaderCircle,
  LogIn,
  MessageSquare,
  MessagesSquare,
  MonitorUp,
  Network,
  Play,
  Power,
  RefreshCw,
  Route,
  ScrollText,
  Search,
  Settings,
  Shield,
  Square,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  X,
  Zap,
} from '@lucide/vue'

// icons 将界面语义名映射到 Lucide 图标
export const icons = {
  logs: ScrollText,
  accounts: KeyRound,
  models: Boxes,
  requests: Activity,
  usage: ChartColumn,
  settings: Settings,
  playground: MessagesSquare,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  close: X,
  check: Check,
  spinner: LoaderCircle,
  play: Play,
  stop: Square,
  stopGeneration: CircleStop,
  trash: Trash2,
  refresh: RefreshCw,
  login: LogIn,
  remote: MonitorUp,
  chat: MessageSquare,
  undo: Undo2,
  copy: Copy,
  warning: TriangleAlert,
  up: ArrowUpRight,
  down: ArrowDownRight,
  latency: Timer,
  tokens: Coins,
  firstEvent: Clock,
  service: Power,
  capacity: Gauge,
  network: Network,
  security: Shield,
  channel: Route,
  calendar: CalendarRange,
  chevronLeft: ChevronLeft,
  filter: ListFilter,
  download: Download,
  columns: Columns3,
  search: Search,
  throughput: Zap,
  success: CircleCheck,
  empty: Inbox,
  send: ArrowUp,
  options: SlidersHorizontal,
  newChat: SquarePen,
  reasoning: Brain,
  tool: Wrench,
  raw: Code,
  modeImage: Image,
  modeSpeech: AudioLines,
  modeMusic: Music,
  modeVideo: Clapperboard,
} as const

// IconName 是界面可用的图标语义名
export type IconName = keyof typeof icons
